development:
#  adapter: async
  adapter: postgresql

test:
#  adapter: postgresql
  adapter: async

production:
#  adapter: redis
  adapter: postgresql
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: dammy-chat-server_production
